// Resumen FIJO de cómo funciona HampiYura, para las preguntas de ayuda/navegación. Cada línea describe algo que EXISTE hoy; si una función
// no está aquí, el asistente no debe afirmar que existe. Al agregar o cambiar funciones de la plataforma, actualizar este texto.
export const RESUMEN_PLATAFORMA = [
  'Catálogo de plantas: sección "Plantas" del menú. Lista las plantas amazónicas ya validadas por especialistas; al abrir una se ven sus partes medicinales y usos, las publicaciones, las fichas de cultivo y su estado de conservación.',
  'Proponer una planta nueva: hace falta iniciar sesión. En el catálogo, botón "Proponer planta": datos de la planta, hábitat, ubicación opcional en el mapa y de 1 a 8 partes medicinales con su uso y su fuente. La propuesta queda pendiente hasta que un especialista la revisa; nada se publica sin esa validación.',
  'Tipos de conocimiento: cada uso de una planta es Tradicional, Documentado o Científico. Solo un uso Científico validado y con evidencia registrada por un especialista se muestra como verificado; Tradicional y Documentado son sugerencias no verificadas científicamente.',
  'Mapa de cultivo: muestra dónde se cultivan plantas, solo con fichas de cultivo ya validadas. Si una planta está en riesgo de conservación no se publican coordenadas exactas, solo la zona.',
  'Ficha de cultivo: la registran únicamente especialistas y administradores (menú de gestión) y queda pendiente hasta ser validada. Cada ficha puede tener una guía para cultivarla (suelo, nutrientes, calendario, riego, clima, plagas, cosecha y marco legal) que redacta un especialista en agronomía; si está vacía, aún no fue completada. Se ve en el detalle de cada planta, en "Fichas de cultivo".',
  'Marco legal: cultivar o cosechar plantas silvestres nativas puede requerir autorización de SERFOR, y el conocimiento tradicional está protegido por la Ley 27811. La información es orientativa y HampiYura no da permisos legales.',
  'Publicaciones de la comunidad: cualquier persona con cuenta puede publicar y comentar; las publicaciones pasan por validación.',
  'Productos: directorio de productos elaborados con plantas. Publicar un producto requiere una cuenta de Productor y aceptar una comisión del 5% sobre ventas; el producto queda pendiente de validación.',
  'Cambiar tipo de cuenta: en "Mi perfil" se puede solicitar ser Productor, Empresario o Institución de investigación. Lo aprueba un administrador y es gratis; no depende de ningún plan.',
  'Directorio de productores y planes de contacto: la información de la plataforma es gratis. Para ver el contacto de un productor hay que tener un plan o desbloquear a ese productor. Planes de referencia: Explorador (gratis), Desbloqueo puntual (S/ 4 por 30 días de un productor), Negocio (S/ 29 al mes), Empresarial (S/ 99 al mes, agrega filtros avanzados del directorio) e Institucional (S/ 120 al mes, agrega soporte prioritario). El pago es por Yape o Plin y un administrador lo confirma.',
  'Enviar consulta: en el pie de página, "Consultas y ayuda". Se puede enviar sin cuenta; con cuenta se puede ver el estado en "Mis consultas". Sirve para hablar con el equipo de especialistas.',
  'Cuenta: para registrarse hay que crear una cuenta y activarla; los especialistas y administradores los asigna el equipo. Las notificaciones (campana) avisan de validaciones, consultas y pagos.',
].join('\n');
