// Ronda 29 — Fotos, hábitat/ubicación y preparaciones de las 27 plantas cargadas en la Ronda 28.
// Fuente: docs/plantas medicinales/Fichas_Habitat_Foto_Preparacion.md (hábitat: Kew POWO; fotos: Wikimedia Commons / GBIF-iNaturalist,
// con autor y licencia verificados por consulta directa a la API de Commons y de GBIF; preparaciones: texto "Preparación" de
// Plantas_Medicinales_Uso_Tradicional_1.docx). Regla RF-252/RF-257: un campo sin dato queda VACÍO, nunca se completa con conocimiento general.

export interface FotoPlanta { url: string; autor: string; licencia: string; fuenteUrl: string }
export interface PrepDoc {
  // Identifica la fila Parte+Uso de la Ronda 28 a la que cuelga la preparación (solo filas Tradicional).
  parte: string; parteDetalle?: string; uso: string;
  formaTradicionalElaboracion: string; pasos?: string; advertencias?: string; localidad: string;
}
export interface FichaPlanta { bin: string; habitat: string; foto: FotoPlanta | null; preparaciones: PrepDoc[] }

const POWO = (id: string) => `https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:${id}`;
const habitat = (texto: string, id: string, extra = '') => `${texto} Fuente: Kew POWO — ${POWO(id)}${extra}`;
// Foto de Wikimedia Commons: se sirve con Special:FilePath (redirige al archivo real, con ancho limitado).
const commons = (archivo: string, autor: string, licencia: string): FotoPlanta => ({
  url: `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(archivo)}?width=960`, autor, licencia,
  fuenteUrl: `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(archivo).replace(/%2C/g, ',').replace(/%28/g, '(').replace(/%29/g, ')')}`,
});
const inat = (idFoto: string, ext: string, autor: string, licencia: string, fuenteUrl: string): FotoPlanta => ({
  url: `https://inaturalist-open-data.s3.amazonaws.com/photos/${idFoto}/large.${ext}`, autor, licencia, fuenteUrl,
});

const ALTOANDINA = ' Nota del equipo (Ronda 29): en Tingo María y la selva esta especie se comercializa, pero no se cultiva localmente.';

export const FICHAS_PLANTAS: FichaPlanta[] = [
  { bin: 'Zea mays',
    habitat: habitat('Nativo de Mesoamérica (centro y suroeste de México a oeste de Guatemala). No es nativo de la Amazonía; en Tingo María es cultivo introducido.', '426810-1'),
    foto: commons('Zea_mays_003.JPG', 'H. Zell', 'CC BY-SA 3.0'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Estigmas de la mazorca (pelo de choclo)', uso: 'Diurético',
      formaTradicionalElaboracion: 'Té o infusión de los estigmas secos ("pelo de choclo").',
      localidad: 'Medicina tradicional china, pueblos nativos de América, Turquía, Vietnam y Francia' }] },
  { bin: 'Coffea arabica',
    habitat: habitat('Nativo del noreste de África tropical (S. Sudán del Sur, SO. Etiopía, N. Kenia, 950-1950 m). Introducido en Perú/Amazonía como cultivo comercial.', '747038-1/general-information'),
    foto: commons('Coffea_arabica_003.JPG', 'H. Zell', 'CC BY-SA 3.0'),
    preparaciones: [] }, // sin uso medicinal tradicional documentado: no se crea preparación
  { bin: 'Musa spp.',
    habitat: habitat('Nativo del Asia tropical y subtropical; llegó a América tras el contacto europeo, hoy cultivado en toda la Amazonía.', '797527-1'),
    foto: commons('Musa_acuminata_15zz.jpg', 'David J. Stang', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Cáscara', uso: 'Cicatrizante',
      formaTradicionalElaboracion: 'Cáscara aplicada directamente sobre la piel (uso tópico); otras partes (raíz, pseudotallo, hojas, flores) en preparados locales.',
      localidad: 'Medicina tradicional de América, Asia, Oceanía, India y África' }] },
  { bin: 'Theobroma cacao',
    habitat: habitat('Nativo de América tropical, incluida la cuenca amazónica peruana.', '320783-2'),
    foto: commons('Theobroma_cacao_Fruits.jpg', 'Hiobson', 'CC BY-SA 4.0'),
    preparaciones: [
      { parte: 'Semilla', parteDetalle: 'Cáscara de la semilla cocida', uso: 'Respiratorio', formaTradicionalElaboracion: 'Cocimiento de la cáscara de la semilla (uso amazónico peruano para la tos seca).', localidad: 'Pueblos amazónicos peruanos' },
      { parte: 'Semilla', parteDetalle: 'Semillas, flores, manteca y hojas (usos históricos)', uso: 'Otro', formaTradicionalElaboracion: 'Bebidas y pastas de cacao; manteca en uso externo.', localidad: 'Mayas y aztecas; médicos coloniales europeos' },
    ] },
  { bin: 'Persea americana',
    habitat: habitat('Nativo de Mesoamérica (centro de México a Costa Rica). Introducido en la selva peruana.', '325643-2'),
    foto: commons('Persea_americana_fruit.JPG', 'B.navez', 'CC BY-SA 3.0'),
    preparaciones: [
      { parte: 'Hoja', uso: 'Otro', formaTradicionalElaboracion: 'Infusión o cocimiento de hojas.', localidad: 'Sudamérica, Centroamérica y África' },
      { parte: 'Semilla', parteDetalle: 'Semilla (pepa)', uso: 'Odontológico', formaTradicionalElaboracion: 'Extractos de la semilla.', localidad: 'Sudamérica, Centroamérica y África' },
      { parte: 'Fruto', uso: 'Dermatológico', formaTradicionalElaboracion: 'Fruto en polvo o macerado sobre la piel.', localidad: 'Sudamérica, Centroamérica y África' },
      { parte: 'Corteza', parteDetalle: 'Corteza y tallo', uso: 'Otro', formaTradicionalElaboracion: 'Cocimiento de corteza.', localidad: 'Sudamérica, Centroamérica y África' },
    ] },
  { bin: 'Annona muricata',
    habitat: habitat('Nativo desde el sur de México hasta Venezuela y Perú — sí forma parte de su rango nativo en la Amazonía peruana.', '14308-2'),
    foto: commons('Annona_muricata_1.jpg', 'Damien Boilley', 'CC BY 2.0'),
    preparaciones: [
      { parte: 'Hoja', uso: 'Antiparasitario', formaTradicionalElaboracion: 'Jugo obtenido de siete hojas frescas trituradas (Amazonía peruana).', localidad: 'Población mestiza y nativa de la Amazonía peruana' },
      { parte: 'Corteza', parteDetalle: 'Corteza (también semillas, raíz y fruto)', uso: 'Otro', formaTradicionalElaboracion: 'Infusiones y cocimientos de hojas o corteza.', localidad: 'Medicina tradicional de los trópicos de América, África y Asia' },
    ] },
  { bin: 'Bixa orellana',
    habitat: habitat('Nativo desde México hasta Sudamérica tropical, incluido Perú.', '33335-2'),
    foto: commons('Hojas_de_Achiote_(Bixa_orellana)_en_Takiwasi,_Tarapoto,_Perú.jpg', 'Kristi Denby / Archivo Centro Takiwasi', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Hoja', uso: 'Dermatológico',
      formaTradicionalElaboracion: 'Infusión, cocimiento o remojo de las hojas en agua durante la noche.',
      localidad: 'Pueblos amazónicos peruanos (incluidos los Asháninkas); indígenas de Brasil' }] },
  { bin: 'Mentha piperita',
    habitat: habitat('Híbrido nativo de Europa a Asia Central; introducida y cultivada en el resto del mundo.', '450969-1'),
    foto: commons('Mentha_x_piperita_002.JPG', 'H. Zell', 'CC BY-SA 3.0'),
    preparaciones: [{ parte: 'Hoja', uso: 'Digestivo', formaTradicionalElaboracion: 'Infusión (té) de las hojas.', localidad: 'Medicina tradicional de Europa y de muchos otros países' }] },
  { bin: 'Eucalyptus globulus',
    habitat: habitat('Nativo exclusivamente del sureste de Australia (Victoria/Tasmania). Introducido y cultivado mundialmente, incluido Perú/Andes.', '592965-1'),
    foto: commons('Eucalyptus_globulus-IMG_8730.JPG', 'C T Johansson', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Hoja', uso: 'Respiratorio', formaTradicionalElaboracion: 'Vapor de las hojas hervidas (inhalación) e infusión.', localidad: 'Medicina popular de muchos países' }] },
  { bin: 'Morinda citrifolia',
    habitat: habitat('Nativo del sudeste asiático y Australasia tropical; naturalizado/introducido en América tropical incl. Amazonía (Ucayali, San Martín, Loreto como cultivo comercial).', '756359-1'),
    foto: commons('Hojas_y_fruto_de_Noni_(Morinda_citrifolia).jpg', 'Martín Huamán', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Fruto', parteDetalle: 'Fruto maduro (jugo) y hojas', uso: 'Otro',
      formaTradicionalElaboracion: 'Jugo del fruto maduro, fermentado o fresco; infusión de hojas.',
      localidad: 'Pueblos del Pacífico y del sudeste asiático (uso ancestral); en Perú, cultivo comercial reciente en la Amazonía' }] },
  { bin: 'Plantago major',
    habitat: habitat('Nativo de Europa, norte/centro de Asia, norte y sur de África; naturalizado casi mundialmente, incluida Sudamérica/Amazonía.', '321286-2'),
    foto: commons('20170513Plantago_major1.jpg', 'AnRo0002', 'CC0 1.0 (dominio público)'),
    preparaciones: [{ parte: 'Hoja', parteDetalle: 'Hojas frescas o machacadas', uso: 'Cicatrizante',
      formaTradicionalElaboracion: 'Hoja fresca machacada aplicada directamente (cataplasma); también en cocimiento para lavados.',
      pasos: '1. Machacar la hoja fresca.\n2. Aplicarla directamente sobre la piel (cataplasma).',
      localidad: 'Medicina popular de Perú y de gran parte de América Latina (uso extendido, incluida la zona de Tingo María)' }] },
  { bin: 'Croton lechleri',
    habitat: habitat('Nativo del oeste de Sudamérica: Bolivia, Colombia, Ecuador y Perú (cuenca amazónica, tierras bajas del noroeste).', '342842-1'),
    foto: commons('Sangre_de_grado_(Croton_lechleri)_en_el_jardín_botánico_de_Takiwasi.jpg', 'Jaime Torres / Archivo Centro Takiwasi', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Látex rojo de la corteza', uso: 'Cicatrizante',
      formaTradicionalElaboracion: 'Látex aplicado directamente sobre heridas y picaduras; unas gotas en agua por vía oral.',
      localidad: 'Pueblos indígenas y población de la Amazonía occidental (Perú, Ecuador)' }] },
  { bin: 'Uncaria tomentosa',
    habitat: habitat('Liana nativa de América tropical central y del sur hasta Trinidad, incluido Perú.', '768322-1'),
    foto: commons('Uncaria_tomentosa.png', 'Vangeliq.petrova', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Corteza', parteDetalle: 'Corteza y raíz', uso: 'Otro',
      formaTradicionalElaboracion: 'Cocimiento de corteza o raíz; extracto en alcohol. Uso restringido tradicionalmente a sacerdotes/curanderos Asháninka.',
      localidad: 'Pueblo Asháninka, Selva Central del Perú' }] },
  { bin: 'Phyllanthus niruri',
    habitat: habitat('Nativa de América tropical y subtropical (Argentina a México), incluido Perú.', '194900-2'),
    foto: commons('Chanca_piedra_(Phyllanthus_niruri).jpg', 'Kristi Denby / Archivo Centro Takiwasi', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Raíz y planta entera', uso: 'Diurético',
      formaTradicionalElaboracion: 'Cocimiento (decocción) o infusión de la raíz o de la planta entera.', localidad: 'Población de la Amazonía peruana' }] },
  { bin: 'Maytenus macrocarpa',
    habitat: habitat('Nativa de América tropical del sur: Bolivia, Brasil norte, Colombia, Ecuador, Perú, Venezuela. Revisiones recientes usan el nombre Monteverdia macrocarpa.', '155542-2'),
    foto: commons('Chuchuwasi_(Monteverdia_macrocarpa),_vista_del_árbol_desde_abajo.jpg', 'Kristi Denby', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Corteza', parteDetalle: 'Raíz y corteza', uso: 'Antiinflamatorio',
      formaTradicionalElaboracion: 'Maceración de la corteza en aguardiente (maceración alcohólica) y cocimiento.', localidad: 'Población de la Amazonía peruana' }] },
  { bin: 'Genipa americana',
    habitat: habitat('Nativa desde el sur de México hasta América tropical, incluido Perú.', '751331-1'),
    foto: commons('Jagua_(Genipa_americana)_(14557582148).jpg', 'Alejandro Bayer Tamayo', 'CC BY-SA 2.0'),
    preparaciones: [{ parte: 'Corteza', parteDetalle: 'Corteza, frutos, raíz y semillas', uso: 'Otro',
      formaTradicionalElaboracion: 'Cocimiento, jugo del fruto y jarabe.', localidad: 'Pueblos de la Amazonía peruana y brasileña' }] },
  { bin: 'Dracontium loretense',
    habitat: habitat('Nativa desde Costa Rica hasta América tropical del sur, incluido Perú. Kew POWO trata este nombre como sinónimo del nombre aceptado Dracontium spruceanum (Schott) G.H.Zhu.', '991397-1'),
    foto: commons('Planta_de_Jergón_Sacha_(Dracontium_spruceanum_-_Dracontium_loretense)_en_Takiwasi,_Tarapoto,_Perú.jpg', 'Martín Huamán', 'CC BY-SA 4.0'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Bulbo (tubérculo)', uso: 'Otro',
      formaTradicionalElaboracion: 'Se usa el bulbo (tubérculo) como antiofídico. La fuente original no detalla la forma exacta de preparación.',
      localidad: 'Pueblos nativos de la Amazonía peruana' }] },
  { bin: 'Plukenetia volubilis',
    habitat: habitat('Nativa desde las Antillas de Barlovento hasta América tropical del sur, incluido Perú.', '354970-1'),
    foto: commons('Plukenetia_volubilis_(Sacha_Inchi)_Euphorbiaceae_Peru.png', 'Michael Hermann', 'CC BY-SA 3.0'),
    preparaciones: [
      { parte: 'Semilla', uso: 'Analgésico', formaTradicionalElaboracion: 'Semillas tostadas.', localidad: 'Pueblos Mayoruna, Campa (Asháninka), Huitoto, Shipibo, Yagua y Bora' },
      { parte: 'Semilla', parteDetalle: 'Semillas molidas con aceite (crema)', uso: 'Dermatológico', formaTradicionalElaboracion: 'Crema de semilla molida con aceite.', localidad: 'Pueblos Mayoruna, Campa (Asháninka), Huitoto, Shipibo, Yagua y Bora' },
    ] },
  { bin: 'Myrciaria dubia',
    habitat: habitat('Nativa de la Amazonía sudamericana (incl. Perú), típicamente en orillas de ríos y zonas inundables (várzea).', '166146-2'),
    foto: inat('481971342', 'jpeg', 'Floyd E. Hayes', 'CC BY-NC 4.0', 'https://www.gbif.org/occurrence/5133730132'),
    preparaciones: [{ parte: 'Fruto', parteDetalle: 'Fruto (también hojas y semillas)', uso: 'Alimenticio/Nutricional',
      formaTradicionalElaboracion: 'Jugo del fruto, fresco o fermentado.', localidad: 'Poblaciones de Perú, Brasil, Colombia, Ecuador y Venezuela' }] },
  { bin: 'Petiveria alliacea',
    habitat: habitat('Nativa de América tropical/subtropical, incluido Perú; introducida en partes de África y Asia.', '323288-2'),
    foto: inat('262606529', 'jpeg', 'Diego Salinas Bardales', 'CC BY-NC 4.0', 'https://www.gbif.org/occurrence/4982070460'),
    preparaciones: [{ parte: 'Raíz', parteDetalle: 'Raíz y hojas', uso: 'Antiinflamatorio',
      formaTradicionalElaboracion: 'Raíces, hojas o polvo de la planta.', localidad: 'Pueblos amazónicos y del Caribe; religiones afrobrasileñas' }] },
  { bin: 'Copaifera spp.',
    habitat: habitat('Nativa de Bolivia, norte de Brasil y Perú, bioma tropical estacionalmente seco (especie representativa del género: Copaifera paupera (Herzog) Dwyer).', '64942-2'),
    foto: inat('152941632', 'jpg', 'Ymber Flores B', 'CC BY-NC 4.0', 'https://www.gbif.org/occurrence/4891926283'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Oleorresina (resina) extraída del tronco por incisión', uso: 'Cicatrizante',
      formaTradicionalElaboracion: 'Resina (oleorresina) aplicada directamente sobre la piel o mucosas; unas gotas por vía oral en agua o miel.',
      localidad: 'Pueblos y población mestiza de la Amazonía peruana (Ucayali, Madre de Dios, Loreto)' }] },
  { bin: 'Ficus insipida',
    habitat: habitat('Rango nativo amplio desde México y Centroamérica hasta Sudamérica, incluido Perú.', '853024-1'),
    foto: inat('544215611', 'jpg', 'Alfredo Gutierrez Dipaz', 'CC BY 4.0', 'https://www.gbif.org/occurrence/5760010316'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Látex (savia lechosa) del tronco', uso: 'Antiparasitario',
      formaTradicionalElaboracion: 'Látex tomado directamente por vía oral, en la dosis tradicional de aproximadamente 1 cm³ por kg de peso corporal.',
      advertencias: 'ADVERTENCIA: es la planta con toxicidad documentada y cuantificada más alta de las fichas: riesgo documentado de sobredosis, con un registro real de muertes (estudio Hansson et al. 2005). No usar sin la dosis y la supervisión de un especialista.',
      localidad: 'Población de Pucallpa (Ucayali) y de la Amazonía peruana en general' }] },
  { bin: 'Piper aduncum',
    habitat: habitat('Nativa de amplio rango en América tropical, incluido Perú.', '680296-1'),
    foto: inat('347662924', 'jpeg', 'Monics Paredes', 'CC BY 4.0', 'https://www.gbif.org/occurrence/5237753363'),
    preparaciones: [{ parte: 'Hoja', uso: 'Cicatrizante',
      formaTradicionalElaboracion: 'Decocción de las hojas para lavado externo de heridas o como bebida; cataplasma de hojas machacadas.', localidad: 'Población de la Amazonía peruana (de la costa a la selva)' }] },
  { bin: 'Gentianella alborosea',
    habitat: habitat('Andes altos del Perú (Kew POWO da como rango nativo confirmado solo "Perú (Junín)"), bioma altoandino/subalpino — no es planta amazónica de tierras bajas; en Tingo María/la selva se vende como insumo comercializado, no cultivado localmente.', '108636-2', ' · Apoyo etnobotánico: https://ethnobotanyjournal.org/index.php/era/article/view/1813'),
    foto: commons('Gentianella_alborosea.JPG', 'R. Mathis', 'CC BY 3.0'),
    preparaciones: [{ parte: 'Otra', parteDetalle: 'Partes aéreas secas', uso: 'Hepatoprotector',
      formaTradicionalElaboracion: 'Infusión de la planta seca.', localidad: 'Medicina popular del Perú (documentado en el norte del país)' }] },
  { bin: 'Smallanthus sonchifolius',
    habitat: habitat('Nativo del oeste de Sudamérica (Bolivia, Colombia, Ecuador, Perú), cultivado tradicionalmente en valles altoandinos, no en selva baja.', '237510-2', ALTOANDINA),
    foto: commons('Yacon_plant_(Smallanthus_sonchifolius).JPG', 'NusHub', 'CC BY-SA 3.0'),
    preparaciones: [
      { parte: 'Raíz', parteDetalle: 'Raíz tuberosa', uso: 'Alimenticio/Nutricional', formaTradicionalElaboracion: 'Raíz fresca o en jugo (alimento dulce bajo en calorías).', localidad: 'Poblaciones andinas y amazónicas del Perú, Ecuador, Bolivia y Argentina' },
      { parte: 'Hoja', uso: 'Otro', formaTradicionalElaboracion: 'Hojas en infusión, tradicionalmente para la diabetes.', localidad: 'Poblaciones andinas y amazónicas del Perú, Ecuador, Bolivia y Argentina' },
    ] },
  { bin: 'Ilex guayusa',
    habitat: habitat('Oeste de Sudamérica hasta Venezuela, incluido Perú — sí es especie de selva baja amazónica.', '127854-2'),
    foto: commons('View_of_Ilex_guayusa_from_above.jpg', 'Anna Premo', 'Licencia Arte Libre (FAL)'),
    preparaciones: [{ parte: 'Hoja', parteDetalle: 'Hojas tostadas o secas, en infusión', uso: 'Ritual/Espiritual',
      formaTradicionalElaboracion: 'Hojas hervidas durante la noche; bebida tomada antes del amanecer (uso ritual).',
      pasos: '1. Hervir las hojas durante la noche.\n2. Beber la bebida antes del amanecer.',
      localidad: 'Pueblos jíbaros (Achuar, Shuar) y Kichwa de la Amazonía de Perú y Ecuador' }] },
  { bin: 'Mansoa alliacea',
    habitat: habitat('Amplia distribución en la cuenca amazónica y el Caribe, incluido Perú.', '152672-2'),
    foto: commons('Planta_de_Ajo_Sacha_(Mansoa_alliacea).jpg', 'François Delonnay', 'CC BY-SA 4.0'),
    // Sin uso tradicional documentado: el único texto es un protocolo de laboratorio en ratones, que NO se presenta como preparación
    // (el formulario y su aviso son de conocimiento tradicional; las dosis animales podrían leerse como dosis humanas).
    preparaciones: [] },
];
