import { Router } from 'express';
import { estadoAsistente, consultarAsistente } from '../controllers/m12-busqueda-recomendaciones/asistente.controller';
import { registrar, login, activarCuenta, solicitarRecuperacion, restablecerContraseña, cambiarContraseña, obtenerPerfil, actualizarPerfil, solicitarTipoCuenta, obtenerMiTipoCuenta } from '../controllers/m01-cuentas.controller';
import { registrarPlanta, proponerPlanta, listarPlantas, obtenerPlanta } from '../controllers/m02-catalogo-plantas/plantas.controller';
import { registrarFicha, obtenerFicha, listarFichasPorPlanta, registrarUbicacionCultivo, obtenerUbicacionCultivo, listarMapaCultivo, actualizarGuiaCultivo } from '../controllers/m03-cultivo.controller';
import { registrarUso, listarUsos } from '../controllers/m04-usos-partes/usos.controller';
import { registrarParteUso, obtenerParteUso, listarPartesUsoPorPlanta, listarSeguimiento, obtenerSeguimiento, actualizarContactoSeguimiento, registrarValidacionCientifica } from '../controllers/m04-usos-partes/partes-uso.controller';
import { crearPublicacion, obtenerPublicacion, listarPublicaciones, editarPublicacion, eliminarPublicacion, subirMedia } from '../controllers/m06-publicaciones/publicaciones.controller';
import { comentarPublicacion, listarComentarios, calificarPublicacion } from '../controllers/m07-comunidad/comunidad.controller';
import { aprobar, observar, rechazar, listarPendientes, detalleValidacion, reportar, listarReportes, actualizarEstadoReporte } from '../controllers/m09-validacion.controller';
import { obtenerPanel, listarUsuarios, suspenderUsuario, reactivarUsuario, cambiarRolUsuario, eliminarPlanta, obtenerAuditoria } from '../controllers/m13-analitica-estadisticas/administracion.controller';
import { listarNotificaciones, marcarTodasLeidas, marcarLeida, eliminarNotificacion } from '../controllers/m14-seguridad-notificaciones/notificaciones.controller';
import { documentarPreparacion, obtenerPreparacion, listarPreparaciones } from '../controllers/m05-preparaciones/preparaciones.controller';
import { publicarProducto, obtenerProducto, listarProductos, listarZonasGenerales, marcarValidadoDocumentalmente, marcarCertificado, verificarAfirmaciones } from '../controllers/m11-productos-emprendimientos/productos.controller';
import { registrarEstadoConservacion, obtenerEstadoConservacion, registrarAccionConservacion, listarAccionesConservacion } from '../controllers/m10-conservacion/conservacion.controller';
import { buscarPlantas } from '../controllers/m12-busqueda-recomendaciones/busqueda.controller';
import { crearConsulta, listarBandejaConsultas, listarMisConsultas, obtenerConsulta, agregarMensajeConsulta, cambiarEstadoConsulta, asignarConsulta } from '../controllers/m08-consultas/consultas.controller';
import { listarPlanes, miPlan, solicitarPago, listarPagos, detallePago, confirmarPago, rechazarPago, listarProductores, obtenerProductor } from '../controllers/m15-planes/planes.controller';
import { listarConversaciones, mensajesSinLeer, obtenerConversacion, escribirAProductor, responderConversacion, listarAlertas, seguirPlanta, dejarDeSeguir, procesarAlertas, reporteBioeconomia, accesoDisponibles, listarDisponibles, miDisponibilidad, marcarDisponibilidad } from '../controllers/m15-planes/extras.controller';
import { estadoCompra, obtenerCobro, configurarCobro, vistaPreviaPedido, crearPedido, misPedidos, reclamosPendientes, obtenerPedido, informarPago, confirmarPagoPedido, rechazarPagoPedido, marcarEnviado, confirmarRecepcion, abrirReclamo, resolverReclamo, cancelarPedido } from '../controllers/m16-pedidos/pedidos.controller';
import { requireAuth, requireValidator, requireAdmin, requireProductor, attachUserIfPresent } from '../middlewares/role.middleware';
export const router=Router();
// M-15 · Contacto pagado y planes
router.get('/planes',listarPlanes); router.get('/planes/mi-plan',requireAuth,miPlan); router.post('/planes/pagos',requireAuth,solicitarPago);
router.get('/planes/pagos',requireAdmin,listarPagos); router.get('/planes/pagos/:id',requireAdmin,detallePago); router.post('/planes/pagos/:id/confirmar',requireAdmin,confirmarPago); router.post('/planes/pagos/:id/rechazar',requireAdmin,rechazarPago);
router.get('/asistente/estado',estadoAsistente); router.post('/asistente/consulta',attachUserIfPresent,consultarAsistente);
// Ronda 30: mensajería (plan Negocio), alertas (plan Negocio), reportes (plan Institucional) y productores disponibles (complemento Premium)
router.get('/mensajes/conversaciones',requireAuth,listarConversaciones); router.get('/mensajes/sin-leer',requireAuth,mensajesSinLeer); router.get('/mensajes/conversaciones/:id',requireAuth,obtenerConversacion); router.post('/mensajes',requireAuth,escribirAProductor); router.post('/mensajes/conversaciones/:id',requireAuth,responderConversacion);
router.get('/alertas',requireAuth,listarAlertas); router.post('/alertas',requireAuth,seguirPlanta); router.delete('/alertas/:plantaId',requireAuth,dejarDeSeguir); router.post('/alertas/procesar',requireAdmin,procesarAlertas);
router.get('/reportes/bioeconomia',requireAuth,reporteBioeconomia);
router.get('/productores-disponibles/acceso',attachUserIfPresent,accesoDisponibles); router.get('/productores-disponibles',requireAuth,listarDisponibles); router.get('/productores-disponibles/mi-estado',requireAuth,miDisponibilidad); router.put('/productores-disponibles/mi-estado',requireAuth,marcarDisponibilidad);
// Ronda 35 · M-16: compra directa (Yape/Plin/cuenta) con contrato
router.get('/productos/:id/estado-compra',attachUserIfPresent,estadoCompra); router.get('/productos/:id/cobro',requireAuth,obtenerCobro); router.put('/productos/:id/cobro',requireAuth,configurarCobro);
router.post('/pedidos/vista-previa',requireAuth,vistaPreviaPedido); router.post('/pedidos',requireAuth,crearPedido); router.get('/pedidos',requireAuth,misPedidos); router.get('/pedidos/reclamos',requireAdmin,reclamosPendientes); router.get('/pedidos/:id',requireAuth,obtenerPedido);
router.post('/pedidos/:id/pago',requireAuth,informarPago); router.post('/pedidos/:id/confirmar-pago',requireAuth,confirmarPagoPedido); router.post('/pedidos/:id/rechazar-pago',requireAuth,rechazarPagoPedido); router.post('/pedidos/:id/enviado',requireAuth,marcarEnviado);
router.post('/pedidos/:id/recibido',requireAuth,confirmarRecepcion); router.post('/pedidos/:id/reclamo',requireAuth,abrirReclamo); router.post('/pedidos/:id/resolver',requireAdmin,resolverReclamo); router.post('/pedidos/:id/cancelar',requireAuth,cancelarPedido);
router.get('/productores',attachUserIfPresent,listarProductores); router.get('/productores/:id',attachUserIfPresent,obtenerProductor);
router.post('/cuentas/solicitud-tipo-cuenta',requireAuth,solicitarTipoCuenta); router.get('/cuentas/solicitud-tipo-cuenta',requireAuth,obtenerMiTipoCuenta);
router.post('/cuentas/registro',registrar); router.post('/cuentas/login',login); router.post('/cuentas/activar',activarCuenta); router.post('/cuentas/recuperar-contrasena',solicitarRecuperacion); router.post('/cuentas/restablecer-contrasena',restablecerContraseña); router.post('/cuentas/cambiar-contrasena',requireAuth,cambiarContraseña); router.get('/cuentas/perfil',requireAuth,obtenerPerfil); router.patch('/cuentas/perfil',requireAuth,actualizarPerfil);
router.post('/plantas',requireValidator,registrarPlanta); router.post('/plantas/proponer',requireAuth,proponerPlanta); router.get('/plantas',listarPlantas); router.get('/plantas/:id',obtenerPlanta);
router.post('/cultivos',requireValidator,registrarFicha); router.patch('/cultivos/:id/guia',requireValidator,actualizarGuiaCultivo); router.get('/cultivos/:id',obtenerFicha); router.get('/plantas/:plantaId/cultivos',listarFichasPorPlanta);
router.post('/cultivos/:cultivoId/ubicacion',requireAuth,registrarUbicacionCultivo); router.get('/cultivos/:cultivoId/ubicacion',obtenerUbicacionCultivo);
router.get('/mapa-cultivo',attachUserIfPresent,listarMapaCultivo);
router.post('/usos',requireValidator,registrarUso); router.get('/usos',listarUsos);
router.post('/partes-uso',requireAuth,registrarParteUso); router.get('/partes-uso/seguimiento',requireValidator,listarSeguimiento); router.get('/partes-uso/seguimiento/:id',requireValidator,obtenerSeguimiento); router.patch('/partes-uso/seguimiento/:id/contacto',requireValidator,actualizarContactoSeguimiento); router.post('/partes-uso/seguimiento/:id/validacion-cientifica',requireValidator,registrarValidacionCientifica);
router.get('/partes-uso/:id',obtenerParteUso); router.get('/plantas/:plantaId/partes-uso',listarPartesUsoPorPlanta);
router.post('/publicaciones/media',requireAuth,subirMedia);
router.post('/publicaciones',requireAuth,crearPublicacion); router.get('/publicaciones',listarPublicaciones); router.get('/publicaciones/:id',attachUserIfPresent,obtenerPublicacion); router.patch('/publicaciones/:id',requireAuth,editarPublicacion); router.delete('/publicaciones/:id',requireAuth,eliminarPublicacion);
router.post('/publicaciones/:publicacionId/comentarios',requireAuth,comentarPublicacion); router.get('/publicaciones/:publicacionId/comentarios',listarComentarios);
router.post('/publicaciones/:publicacionId/calificacion',requireAuth,calificarPublicacion);
router.get('/validaciones/pendientes',requireValidator,listarPendientes); router.get('/validaciones/:id/detalle',requireValidator,detalleValidacion);
router.post('/validaciones/:id/aprobar',requireValidator,aprobar); router.post('/validaciones/:id/observar',requireValidator,observar); router.post('/validaciones/:id/rechazar',requireValidator,rechazar);
router.post('/reportes',requireAuth,reportar); router.get('/reportes',requireValidator,listarReportes); router.patch('/reportes/:id',requireValidator,actualizarEstadoReporte);
router.get('/admin/panel',requireValidator,obtenerPanel);
router.get('/admin/usuarios',requireAdmin,listarUsuarios);
router.patch('/admin/usuarios/:id/suspender',requireAdmin,suspenderUsuario); router.patch('/admin/usuarios/:id/reactivar',requireAdmin,reactivarUsuario);
router.patch('/admin/usuarios/:id/rol',requireAdmin,cambiarRolUsuario);
router.delete('/admin/plantas/:id',requireAdmin,eliminarPlanta);
router.get('/admin/auditoria',requireAdmin,obtenerAuditoria);
router.get('/notificaciones',requireAuth,listarNotificaciones); router.patch('/notificaciones/marcar-leidas',requireAuth,marcarTodasLeidas); router.patch('/notificaciones/:id/marcar-leida',requireAuth,marcarLeida); router.delete('/notificaciones/:id',requireAuth,eliminarNotificacion);
router.post('/preparaciones',requireAuth,documentarPreparacion); router.get('/preparaciones/:id',obtenerPreparacion); router.get('/partes-uso/:parteUsoId/preparaciones',listarPreparaciones);
router.post('/productos/verificar-afirmaciones',verificarAfirmaciones); router.get('/productos/zonas',listarZonasGenerales);
router.post('/productos',requireProductor,publicarProducto); router.get('/productos',attachUserIfPresent,listarProductos); router.get('/productos/:id',attachUserIfPresent,obtenerProducto);
router.patch('/productos/:id/validar-documental',requireValidator,marcarValidadoDocumentalmente); router.patch('/productos/:id/certificar',requireValidator,marcarCertificado);
router.post('/plantas/:plantaId/conservacion',requireValidator,registrarEstadoConservacion); router.get('/plantas/:plantaId/conservacion',obtenerEstadoConservacion);
router.post('/plantas/:plantaId/acciones-conservacion',requireAuth,registrarAccionConservacion); router.get('/plantas/:plantaId/acciones-conservacion',listarAccionesConservacion);
router.get('/buscar',buscarPlantas);
router.post('/consultas',attachUserIfPresent,crearConsulta);
router.get('/consultas',requireValidator,listarBandejaConsultas);
router.get('/consultas/mias',requireAuth,listarMisConsultas);
router.get('/consultas/:id',requireAuth,obtenerConsulta);
router.post('/consultas/:id/mensajes',requireAuth,agregarMensajeConsulta);
router.patch('/consultas/:id/estado',requireAuth,cambiarEstadoConsulta);
router.patch('/consultas/:id/asignar',requireAdmin,asignarConsulta);
