import { Router } from 'express';
import { registrar, login, activarCuenta, solicitarRecuperacion, restablecerContraseña, cambiarContraseña, obtenerPerfil } from '../controllers/m01-cuentas.controller';
import { registrarPlanta, listarPlantas, obtenerPlanta } from '../controllers/m02-catalogo-plantas/plantas.controller';
import { registrarFicha, obtenerFicha, listarFichasPorPlanta, registrarUbicacionCultivo, obtenerUbicacionCultivo, listarMapaCultivo } from '../controllers/m03-cultivo.controller';
import { registrarUso, listarUsos } from '../controllers/m04-usos-partes/usos.controller';
import { registrarParteUso, obtenerParteUso, listarPartesUsoPorPlanta } from '../controllers/m04-usos-partes/partes-uso.controller';
import { crearPublicacion, obtenerPublicacion, listarPublicaciones, editarPublicacion, eliminarPublicacion, subirMedia } from '../controllers/m06-publicaciones/publicaciones.controller';
import { comentarPublicacion, listarComentarios, calificarPublicacion } from '../controllers/m07-comunidad/comunidad.controller';
import { aprobar, observar, rechazar, listarPendientes, reportar, listarReportes, actualizarEstadoReporte } from '../controllers/m09-validacion.controller';
import { obtenerPanel, listarUsuarios, suspenderUsuario, reactivarUsuario, cambiarRolUsuario, eliminarPlanta, obtenerAuditoria } from '../controllers/m13-analitica-estadisticas/administracion.controller';
import { listarNotificaciones, marcarTodasLeidas, marcarLeida, eliminarNotificacion } from '../controllers/m14-seguridad-notificaciones/notificaciones.controller';
import { documentarPreparacion, obtenerPreparacion, listarPreparaciones } from '../controllers/m05-preparaciones/preparaciones.controller';
import { publicarProducto, obtenerProducto, listarProductos, marcarValidadoDocumentalmente, marcarCertificado, verificarAfirmaciones } from '../controllers/m11-productos-emprendimientos/productos.controller';
import { registrarEstadoConservacion, obtenerEstadoConservacion, registrarAccionConservacion, listarAccionesConservacion } from '../controllers/m10-conservacion/conservacion.controller';
import { buscarPlantas } from '../controllers/m12-busqueda-recomendaciones/busqueda.controller';
import { crearConsulta, listarBandejaConsultas, listarMisConsultas, obtenerConsulta, agregarMensajeConsulta, cambiarEstadoConsulta, asignarConsulta } from '../controllers/m08-consultas/consultas.controller';
import { requireAuth, requireValidator, requireAdmin, requireProductor, attachUserIfPresent } from '../middlewares/role.middleware';
export const router=Router();
router.post('/cuentas/registro',registrar); router.post('/cuentas/login',login); router.post('/cuentas/activar',activarCuenta); router.post('/cuentas/recuperar-contrasena',solicitarRecuperacion); router.post('/cuentas/restablecer-contrasena',restablecerContraseña); router.post('/cuentas/cambiar-contrasena',requireAuth,cambiarContraseña); router.get('/cuentas/perfil',requireAuth,obtenerPerfil);
router.post('/plantas',requireValidator,registrarPlanta); router.get('/plantas',listarPlantas); router.get('/plantas/:id',obtenerPlanta);
router.post('/cultivos',requireValidator,registrarFicha); router.get('/cultivos/:id',obtenerFicha); router.get('/plantas/:plantaId/cultivos',listarFichasPorPlanta);
router.post('/cultivos/:cultivoId/ubicacion',requireAuth,registrarUbicacionCultivo); router.get('/cultivos/:cultivoId/ubicacion',obtenerUbicacionCultivo);
router.get('/mapa-cultivo',listarMapaCultivo);
router.post('/usos',requireValidator,registrarUso); router.get('/usos',listarUsos);
router.post('/partes-uso',requireAuth,registrarParteUso); router.get('/partes-uso/:id',obtenerParteUso); router.get('/plantas/:plantaId/partes-uso',listarPartesUsoPorPlanta);
router.post('/publicaciones/media',requireAuth,subirMedia);
router.post('/publicaciones',requireAuth,crearPublicacion); router.get('/publicaciones',listarPublicaciones); router.get('/publicaciones/:id',attachUserIfPresent,obtenerPublicacion); router.patch('/publicaciones/:id',requireAuth,editarPublicacion); router.delete('/publicaciones/:id',requireAuth,eliminarPublicacion);
router.post('/publicaciones/:publicacionId/comentarios',requireAuth,comentarPublicacion); router.get('/publicaciones/:publicacionId/comentarios',listarComentarios);
router.post('/publicaciones/:publicacionId/calificacion',requireAuth,calificarPublicacion);
router.get('/validaciones/pendientes',requireValidator,listarPendientes);
router.post('/validaciones/:id/aprobar',requireValidator,aprobar); router.post('/validaciones/:id/observar',requireValidator,observar); router.post('/validaciones/:id/rechazar',requireValidator,rechazar);
router.post('/reportes',requireAuth,reportar); router.get('/reportes',requireValidator,listarReportes); router.patch('/reportes/:id',requireValidator,actualizarEstadoReporte);
router.get('/admin/panel',requireAdmin,obtenerPanel);
router.get('/admin/usuarios',requireAdmin,listarUsuarios);
router.patch('/admin/usuarios/:id/suspender',requireAdmin,suspenderUsuario); router.patch('/admin/usuarios/:id/reactivar',requireAdmin,reactivarUsuario);
router.patch('/admin/usuarios/:id/rol',requireAdmin,cambiarRolUsuario);
router.delete('/admin/plantas/:id',requireAdmin,eliminarPlanta);
router.get('/admin/auditoria',requireAdmin,obtenerAuditoria);
router.get('/notificaciones',requireAuth,listarNotificaciones); router.patch('/notificaciones/marcar-leidas',requireAuth,marcarTodasLeidas); router.patch('/notificaciones/:id/marcar-leida',requireAuth,marcarLeida); router.delete('/notificaciones/:id',requireAuth,eliminarNotificacion);
router.post('/preparaciones',requireAuth,documentarPreparacion); router.get('/preparaciones/:id',obtenerPreparacion); router.get('/partes-uso/:parteUsoId/preparaciones',listarPreparaciones);
router.post('/productos/verificar-afirmaciones',verificarAfirmaciones);
router.post('/productos',requireProductor,publicarProducto); router.get('/productos',listarProductos); router.get('/productos/:id',obtenerProducto);
router.patch('/productos/:id/validar-documental',requireValidator,marcarValidadoDocumentalmente); router.patch('/productos/:id/certificar',requireValidator,marcarCertificado);
router.post('/plantas/:plantaId/conservacion',requireValidator,registrarEstadoConservacion); router.get('/plantas/:plantaId/conservacion',obtenerEstadoConservacion);
router.post('/plantas/:plantaId/acciones-conservacion',requireAuth,registrarAccionConservacion); router.get('/plantas/:plantaId/acciones-conservacion',listarAccionesConservacion);
router.get('/buscar',buscarPlantas);
router.post('/consultas',attachUserIfPresent,crearConsulta);
router.get('/consultas',requireValidator,listarBandejaConsultas);
router.get('/consultas/mias',requireAuth,listarMisConsultas);
router.get('/consultas/:id',requireAuth,obtenerConsulta);
router.post('/consultas/:id/mensajes',requireAuth,agregarMensajeConsulta);
router.patch('/consultas/:id/estado',requireAuth,cambiarEstadoConsulta);
router.patch('/consultas/:id/asignar',requireAdmin,asignarConsulta);
